name: kaggle-gw
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - ipykernel
  - jupyter
  - jupyterlab
  - mypy
  - pandas
  - pre-commit
  - pytest
  - python=3.9.7
  - pytorch #-gpu
  - seaborn
  - torchaudio
  - torchvision
  - typeguard
  #- pycuda
  - mako

  - pip
  - pip:
      - datargs==0.8.0
      - pycbc
      - wandb
      - efficientnet_pytorch
      - scikit-learn
      #- scikit-cuda
