name: kaggle-gw
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - ipykernel
  - jupyter
  - jupyterlab
  - mypy
  - pandas
  - pre-commit
  - pytest
  - python
  - pytorch #-gpu
  - seaborn
  - torchaudio
  - torchvision
  - typeguard
  - pip
  - pip:
      - datargs
      - pycbc
      - wandb
      - efficientnet_pytorch
