name: gw-models
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - typeguard
  - jupyterlab
  - jupyter
  - pytorch
  - cudatoolkit=11.1
  - torchvision
  - torchaudio
  - pandas
  - seaborn
