name: gw-models
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - typeguard
  - pytorch
  - cudatoolkit=11.1
  - torchvision
  - torchaudio
  - pandas
  - seaborn
  - ipykernel